global:
  resolve_timeout: 5m
  smtp_smarthost: 'mail:1025'
  smtp_from: 'alertmanager@example.com'
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false
route:
  receiver: 'email-notification'
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
receivers:
  - name: 'email-notification'
    email_configs:
      - to: 'youremail@example.com'
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']