services:
  postgres:
    image: "postgres:17"
    ports:
      - "5432:5432"
    volumes:
    - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  keycloak:
    image: "quay.io/keycloak/keycloak:26.2.4"
    command:
      - start-dev
    depends_on:
      - postgres
    ports:
      - "8380:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://postgres:5432/postgres"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "postgres"
      KC_HOSTNAME: "localhost"
volumes:
  db_data:
