services:
  mail:
    image: docker.io/axllent/mailpit:latest
    ports:
      - "8025:8025" # Web UI Port
      - "1025:1025" # SMTP Port
  postgres:
    image: "postgres:17"
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  keycloak:
#    build: .
    image: "quay.io/keycloak/keycloak:26.2.4"
    command: start-dev
    depends_on:
      - postgres
    ports:
      - "8380:8080" # Admin Web UI
      - "9000:9000" # Management Interface, e.g. http://localhost:9000/metrics, http://localhost:9000/health
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
      KC_DB: "postgres"
      KC_DB_URL: "jdbc:postgresql://postgres:5432/postgres"
      KC_DB_USERNAME: "postgres"
      KC_DB_PASSWORD: "postgres"
#      KC_HOSTNAME: "http://localhost:8380"
      KC_HEALTH_ENABLED: "true"
      KC_METRICS_ENABLED: "true"
  prometheus:
    image: prom/prometheus:v3.4.1
    depends_on:
      - keycloak
    volumes:
      - ./config/prometheus.yml/:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana-oss:12.0.2
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  jaeger_data: