{
 "title": "keycloak-general",
 "description": "Visualize all KeyCloak X Metrics",
 "tags": [
  "keycloak x",
  "quarkus",
  "java"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DataSource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Available Processors",
   "type": "stat",
   "description": "Displays the number of processors available to the Java virtual machine. This value may change during a particular invocation of the virtual machine.",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_cpu_availableProcessors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System Load Average",
   "type": "stat",
   "description": "Displays the system load average for the last minute. The system load average is the sum of the number of runnable entities queued to the available processors and the number of runnable entities running on the available processors averaged over a period of time. The way in which the load average is calculated is operating system specific but is typically a damped time-dependent average. If the load average is not available, a negative value is displayed. This attribute is designed to provide a hint about the system load and may be queried frequently. The load average may be unavailable on some platforms where it is expensive to implement this method.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_cpu_systemLoadAverage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "description": "Displays the amount of used heap memory in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "base_memory_usedHeap_bytes", "legendFormat": "Used" },
    { "expr": "base_memory_maxHeap_bytes", "legendFormat": "Max" },
    {
     "expr": "base_memory_committedHeap_bytes",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "Number of idle connections in the pool, available to be acquired",
   "type": "stat",
   "description": "Number of idle connections in the pool, available to be acquired.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "agroal_available_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of times an acquire operation succeeded",
   "type": "timeseries",
   "description": "Number of times an acquire operation succeeded.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "rate(agroal_acquire_count_total[$__rate_interval]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Garbage Collection Count",
   "type": "timeseries",
   "description": "Displays the total number of collections that have occurred. This attribute lists -1 if the collection count is undefined for this collector.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_count[$__rate_interval])) by (action, cause) > 0",
     "legendFormat": "{{action}} {{cause}}"
    }
   ]
  },
  {
   "title": "Number of created connections",
   "type": "timeseries",
   "description": "Number of created connections.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "agroal_creation_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Maximum time an application waited to acquire a connection",
   "type": "stat",
   "description": "Maximum time an application waited to acquire a connection.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agroal_blocking_time_max_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Loaded Class Count",
   "type": "timeseries",
   "description": "Displays the total number of classes that have been loaded since the Java virtual machine has started execution.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Unloaded Class Count",
   "type": "timeseries",
   "description": "Displays the total number of classes unloaded since the Java virtual machine has started execution.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "base_classloader_unloadedClasses_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average time for a connection to be created",
   "type": "stat",
   "description": "Average time for a connection to be created.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agroal_creation_time_average_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of destroyed connections",
   "type": "timeseries",
   "description": "Number of destroyed connections.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "agroal_destroy_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Loaded Class Count",
   "type": "timeseries",
   "description": "Displays the number of classes that are currently loaded in the Java virtual machine.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "base_classloader_loadedClasses_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total time waiting for a connections to be created",
   "type": "stat",
   "description": "Total time waiting for a connections to be created.",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agroal_creation_time_total_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Approximate number of threads blocked, waiting to acquire a connection",
   "type": "stat",
   "description": "Approximate number of threads blocked, waiting to acquire a connection.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "agroal_awaiting_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average time an application waited to acquire a connection",
   "type": "stat",
   "description": "Average time an application waited to acquire a connection.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agroal_blocking_time_average_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number active of connections",
   "type": "stat",
   "description": "Number active of connections.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "agroal_active_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of connections removed from the pool, not counting invalid / idle",
   "type": "timeseries",
   "description": "Number of connections removed from the pool, not counting invalid / idle.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "agroal_flush_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Maximum number of connections active simultaneously",
   "type": "stat",
   "description": "Maximum number of connections active simultaneously.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "agroal_max_used_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of connections removed from the pool for being idle",
   "type": "timeseries",
   "description": "Number of connections removed from the pool for being idle.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "agroal_reap_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of times a leak was detected",
   "type": "timeseries",
   "description": "Number of times a leak was detected.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "agroal_leak_detection_count_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total time applications waited to acquire a connection",
   "type": "stat",
   "description": "Total time applications waited to acquire a connection.",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agroal_blocking_time_total_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum time for a connection to be created",
   "type": "stat",
   "description": "Maximum time for a connection to be created.",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "agroal_creation_time_max_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "stat",
   "description": "Displays the current number of live threads including both daemon and non-daemon threads",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jvm_threads_live_threads", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Daemon Thread Count",
   "type": "stat",
   "description": "Displays the current number of live daemon threads.",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_thread_daemon_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peak Thread Count",
   "type": "stat",
   "description": "Displays the peak live thread count since the Java virtual machine started or peak was reset. This includes daemon and non-daemon threads.",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "base_thread_max_count", "legendFormat": "__auto" }
   ]
  }
 ]
}