apiVersion: 1
groups:
    - orgId: 1
      name: alert-when-under-99.9-availability-within-30-days-reached
      folder: availability
      interval: 1m
      rules:
        - uid: ceriijjmr4we8a
          title: Availability under 99,9% within 30 days
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: cepigtrxbfw8wc
              model:
                editorMode: code
                expr: "count_over_time(\r\n  sum (up{application=\"Keycloak\"}  > 0)[30d:1s]  \r\n) \r\n/\r\ncount_over_time(vector(1)[30d:1s])"
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.999
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          dashboardUid: a383f54e-89dc-4fd7-93fd-4277bbb9d6e3
          panelId: 1
          noDataState: NoData
          execErrState: Error
          for: 1m
          keepFiringFor: 1m
          annotations:
            __dashboardUid__: a383f54e-89dc-4fd7-93fd-4277bbb9d6e3
            __panelId__: "1"
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
