spring:
  application:
    name: "spring-security-oauth-server"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8380/auth/realms/summer"
#          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

logging:
  level:
    "org.springframework.security": trace

server:
  port: 8280