spring:
  application:
    name: "spring-security-oauth-server"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8380/realms/summer"

logging:
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) %highlight([%c]): %highlight(%msg%n%throwable)"
  level:
    root: "WARN"
    "org.springframework.web": "WARN"
    "org.springframework.security": "INFO"
    "de.fred4jupiter.spring.security.oauth.server": "DEBUG"

server:
  port: 8280