spring:
  application:
    name: "spring-security-oauth-demo"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8380/auth/realms/summer"
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8280