spring:
  application:
    name: "spring-security-oauth-server"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8380/realms/summer"

logging:
  level:
    "org.springframework.security": trace

server:
  port: 8280