spring:
  application:
    name: "spring-security-oauth-client"

  security:
    oauth2:
      client:
        registration:
          demo-client:
            client-id: "demo-client"
            scope: openid
            authorization-grant-type: "client_credentials"
            provider: "keycloak"
        provider:
          keycloak:
            issuer-uri: "http://localhost:8380/realms/summer"

server:
  port: 8180