spring:
  application:
    name: "spring-security-oauth-client"

  security:
    oauth2:
      client:
        registration:
          demo-client:
            client-id: "demo-client"
            client-secret: "<PUT SECRET HERE>"
            scope: openid
            authorization-grant-type: "client_credentials"
            provider: "keycloak"
        provider:
          keycloak:
            issuer-uri: "http://localhost:8380/realms/summer"

logging:
  pattern:
    console: "%black(%d{ISO8601}) %highlight(%-5level) %highlight([%c]): %highlight(%msg%n%throwable)"
  level:
    root: "WARN"
    "org.springframework.web": "WARN"
    "org.springframework.security": "INFO"
    "de.fred4jupiter.spring.security.oauth.client": "DEBUG"

server:
  port: 8180